settings:
  title: 'Status Pages of Xlon WU's Blog'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: XW.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: xlon-wu-github-io # unique identifier
    name: On GitHub Pages
    url: 'https://xlon-wu.github.io' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: xlon-wu-pages-dev
    name: On Cloudflare Pages
    url: 'https://xlon-wu.pages.dev'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true
